Paige branch
baikauskaite/chat-client pull request #7
Opened 2022-04-11 10:26 UTC by paigecache

- added who_ok, bad_rqst_hdr, and bad_rqst_body to server_message.py
- added support for commands !who and !quit
- modified the controller to remove the original abstraction (via interact_with_server) in order to get things to work at all -> now the code in that method is just in both login and request_users
- as of now, logging on and !who get two responses from the server, i just don't have the time to debug that

2022-04-11 17:03 UTC, baikauskaite requested changes
I think the `ClientMessage` implementation is good :sunny:
Though I left some comments that some lines should be deleted, and other comments are mostly questions.

2022-04-11 17:03 UTC, baikauskaite commented on controller.py
> +        server.second_handshake()
`server.second_handshake()` is called while constructing the `ServerMessage` object, so there is no need to call `server.second_handshake()` (also it wouldn't make a lot of sense to call it here, because the server might not necessarily respond with a second handshake)

2022-04-11 17:03 UTC, baikauskaite commented on controller.py
> +        server.second_handshake()
For example, I tested this out by choosing a username that already exists, so this doesn't handle the case properly.

2022-04-11 17:03 UTC, baikauskaite commented on controller.py
> +        -2: lambda x: print("Too many clients currently logged in. Try again later."),
I think in this case we can just use your method `quit_program()`? The method `busy()` in `ServerMessage` class already notified that there are too many users logged in at the moment and I guess we can't really do anything about that.

2022-04-11 17:03 UTC, baikauskaite commented on controller.py
> +        server.who_ok()
You don't need to call `server.who_ok()` here, wrote a similar comment for the method `login()`, so you can see there why.

2022-04-11 17:03 UTC, baikauskaite commented on server_message.py
> +    # let's just get it to work fully first, then maybe refactor things
Yes, you're right, it's not really the job of `ServerMessage`, because it's doing printing. If you're okay with refactoring things later, maybe let's do that? This is like the bad decision we'll have to carry around a bit because of me :sweat_smile: Don't really feel like doing this right now, more like implementing the whole protocol.

2022-04-12 11:27 UTC, paigecache commented on controller.py
> +        server.second_handshake()
Ahh got it, I didn't fully see where each method was called in server_message but I know that I understand it now

2022-04-12 11:29 UTC, paigecache commented on controller.py
> +        -2: lambda x: print("Too many clients currently logged in. Try again later."),
Good point, I'll switch that now!

2022-04-12 11:31 UTC, paigecache commented on server_message.py
> +    # let's just get it to work fully first, then maybe refactor things
Yeah I agree, let's get things to work entirely first before making them cleaner! And no worries about the implementation, currently in the controller I'm repeating the same pieces of code over and over again😂 We're just doing what we have to do at this point

2022-04-12 12:21 UTC, baikauskaite approved these changes

2022-04-12 13:18 UTC, baikauskaite approved these changes
I think everything's good! Now you can actually merge it.

2022-04-12 13:25 UTC, merged